CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_ENDPOINT_DISABLE_FALLBACK=y
CONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y
CONFIG_ZMK_USB_BOOT=y
CONFIG_USB_HID_POLL_INTERVAL_MS=16
